name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: checkboxes
    id: checklist
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I am using the latest version of the template
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Clone the template using 'Use this template'
        2. Run './gradlew build'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: If applicable, add logs or error messages
      render: shell
      placeholder: Paste error messages or stack traces here

  - type: input
    id: kotlin-version
    attributes:
      label: Kotlin Version
      description: What version of Kotlin are you using?
      placeholder: e.g., 2.3.0
    validations:
      required: true

  - type: input
    id: gradle-version
    attributes:
      label: Gradle Version
      description: What version of Gradle are you using?
      placeholder: e.g., 9.0.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Which platform(s) are affected?
      multiple: true
      options:
        - JVM
        - Android
        - iOS (arm64)
        - iOS (x64)
        - iOS (Simulator arm64)
        - Linux x64
        - All platforms
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Additional environment details (IDE version, Java version, etc.)
      placeholder: |
        - IDE: IntelliJ IDEA 2024.3
        - Java: OpenJDK 21
        - macOS: 15.2

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, related issues, attempted solutions, etc.

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to submit a PR to fix this bug?
      options:
        - label: I am willing to submit a pull request for this issue
          required: false
