name: Notify Dependabot PR

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    if: github.actor == 'dependabot[bot]'
    uses: Compiled-Platforms/.github/.github/workflows/notify-dependabot.yml@main
    with:
      pr-title: ${{ github.event.pull_request.title }}
      pr-url: ${{ github.event.pull_request.html_url }}
      pr-branch: ${{ github.head_ref }}
      repository: ${{ github.repository }}
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
